---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - grafana.cyberwizzard.com
  resources:
  - dashboardconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.cyberwizzard.com
  resources:
  - dashboardconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - grafana.cyberwizzard.com
  resources:
  - dashboardconfigs/status
  verbs:
  - get
  - patch
  - update
