apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: grafana-operator-controller-manager  # Replace with your operator's service account name
    namespace: grafana-operator-system
roleRef:
  kind: ClusterRole
  name: grafana-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
